# Generated by Django 5.1.7 on 2025-04-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='info2',
            field=models.CharField(default='ww', max_length=300, verbose_name='Details'),
        ),
    ]
