# Generated by Django 5.1.7 on 2025-04-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_story_info2'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(default='ww', max_length=300, verbose_name='Details'),
        ),
    ]
