# Generated by Django 5.1.7 on 2025-04-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0006_alter_story_info_alter_story_info2_alter_story_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='info',
            field=models.CharField(max_length=30000, verbose_name='info'),
        ),
    ]
