# Generated by Django 5.1.7 on 2025-04-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0008_alter_story_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='info',
            field=models.TextField(max_length=15000, verbose_name='info'),
        ),
    ]
