# Generated by Django 5.1.7 on 2025-04-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0011_alter_story_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='story',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='info'),
        ),
    ]
