# Generated by Django 5.1.7 on 2025-04-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0012_alter_story_image_alter_story_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(default='image/default.jpg', upload_to='image'),
        ),
        migrations.AlterField(
            model_name='story',
            name='info',
            field=models.CharField(default='ww', max_length=300, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='story',
            name='info2',
            field=models.CharField(default='ww', max_length=300, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(default='ww', max_length=300, verbose_name='Details'),
        ),
    ]
