# Generated by Django 5.1.7 on 2025-04-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0013_alter_story_image_alter_story_info_alter_story_info2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='info',
            field=models.TextField(default='ww', verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='story',
            name='info2',
            field=models.TextField(default='ww', verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(default='ww', max_length=200, verbose_name='Title'),
        ),
    ]
