# Generated by Django 5.1.7 on 2025-04-21 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0014_alter_story_info_alter_story_info2_alter_story_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
