# Generated by Django 5.1.7 on 2025-04-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0016_story'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Story',
            new_name='Story1',
        ),
    ]
